# Tests the pushed commit(s). If the package.json version changes, builds and creates a new github release with the artifacts

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: CreateReleaseForNewPaceVersion
      uses: justincy/github-action-npm-release@2.0.2
      id: createrelease
    - name: SetupNode
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: SetupYarn
      run: yarn install --frozen-lockfile
    - name: Test
      run: yarn jest
    - name: Build
      run: yarn pkg
    - name: AddReleaseArtifacts
      uses: softprops/action-gh-release@v0.1.14
      if: ${{ steps.createrelease.outputs.released == 'true' }}
      with:
        tag_name: ${{ steps.createrelease.outputs.release_tag }}
        body: Pace Release
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          dist/pace
#          dist/pace-linux-x64.tar.bz2
#          dist/pace-macos-arm64.tar.bz2
#          dist/pace-macos-x64.tar.bz2
#          dist/pace-win-x64.exe.tar.bz2
